apiVersion: v1
kind: Pod
metadata:
  name: taint-pod
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
  tolerations:
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"

#kubectl get nodes
#kubectl taint nodes ip-192-168-30-182.ec2.internal project=roboshop:NoSchedule
#ip-192-168-30-182.ec2.internal now this node is taint. if you create the new pode scheduler select the another node to schedule the pod.
#kubectl apply -f 01-taint-toleration.yaml
#kubectl get pods -o wide
#
