apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:                #Input of the logs
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:                   #output of the logs
      elasticsearch:
        hosts: ["elasticsearch:9200"]
---
apiVersion: apps/v1         #Deploymnet
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    demo: deployment
spec:                      #Replica
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      demo: deployment
  template:                #Subset of deploymnet. Pod creation
    metadata:
      labels:
        app: nginx
        demo: deployment
    spec:                   # Nginx Container creation
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx   #nginx-logs are stored in this emplty directory /var/log/nginx
      - name: filebeat-sidecar         # filebeat container
        image: docker.elastic.co/beats/filebeat:7.17.3
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx #nginx-logs are stored in this emplty directory /var/log/nginx
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml

      volumes:
      - name: nginx-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
            name: filebeat-config
            items:
              - key: filebeat.yml
                path: filebeat.yml

#kubectl apply -f 01.emptyDir.yaml
#kubectl logs nginx-deployment-64c78ff6b6-g7fnj -c filebeat-sidecar   # c means contaner name
#
